type Language = 'en' | 'hi';
type Translations = {
    [lang in Language]: {
        [key: string]: string | { [key: string]: string }
    }
};

const translations: Translations = {
    en: {
        header: {
            title: "ClimaSense",
            subtitle: "Outdoor Comfort Predictor"
        },
        form: {
            locationLabel: "Location",
            locationPlaceholder: "e.g., Udaipur, Rajasthan",
            dateLabel: "Date",
            buttonSubmit: "Get Prediction",
            buttonLoading: "Working...",
            currentLocation: "Use Current Location",
        },
        welcome: {
            title: "Ready for an Adventure?",
            line1: "Use the form to enter a location and date.",
            line2: "Our AI model will find the weather data and predict the outdoor comfort level right here."
        },
        results: {
            predictionFor: "Prediction for:",
            download: "Download",
            predictedComfort: "Predicted Comfort",
            recommendationTitle: "Recommendation",
            weatherDataTitle: "Fetched Weather Data",
            temp: "Temperature",
            humidity: "Humidity",
            wind: "Wind Speed",
            rain: "Chance of Precipitation",
            source: "Prediction generated by {source}."
        },
        loading: {
            weather: "Fetching weather for {location}...",
            comfort: "Predicting outdoor comfort..."
        },
        error: {
            title: "Error Generating Prediction",
            unknown: "An unknown error occurred. Please try again.",
            locationPermission: "Could not get location. Please enable location permissions in your browser."
        },
        language: {
            english: "English",
            hindi: "Hindi"
        }
    },
    hi: {
        header: {
            title: "क्लाइमासेंस",
            subtitle: "बाहरी आराम भविष्यवक्ता"
        },
        form: {
            locationLabel: "स्थान",
            locationPlaceholder: "जैसे, उदयपुर, राजस्थान",
            dateLabel: "तारीख",
            buttonSubmit: "भविष्यवाणी प्राप्त करें",
            buttonLoading: "काम हो रहा है...",
            currentLocation: "वर्तमान स्थान का उपयोग करें",
        },
        welcome: {
            title: "एक साहसिक कार्य के लिए तैयार हैं?",
            line1: "स्थान और तारीख दर्ज करने के लिए फॉर्म का उपयोग करें।",
            line2: "हमारा AI मॉडल मौसम डेटा ढूंढेगा और यहीं पर बाहरी आराम के स्तर की भविष्यवाणी करेगा।"
        },
        results: {
            predictionFor: "के लिए भविष्यवाणी:",
            download: "डाउनलोड",
            predictedComfort: "अनुमानित आराम",
            recommendationTitle: "सिफ़ारिश",
            weatherDataTitle: "प्राप्त मौसम डेटा",
            temp: "तापमान",
            humidity: "आर्द्रता",
            wind: "हवा की गति",
            rain: "वर्षा की संभावना",
            source: "भविष्यवाणी {source} द्वारा उत्पन्न।"
        },
        loading: {
            weather: "{location} के लिए मौसम की जानकारी लाई जा रही है...",
            comfort: "बाहरी आराम का अनुमान लगाया जा रहा है..."
        },
        error: {
            title: "भविष्यवाणी उत्पन्न करने में त्रुटि",
            unknown: "एक अज्ञात त्रुटि हुई। कृपया पुन: प्रयास करें।",
            locationPermission: "स्थान नहीं मिल सका। कृपया अपने ब्राउज़र में स्थान अनुमतियाँ सक्षम करें।"
        },
        language: {
            english: "English",
            hindi: "हिन्दी"
        }
    }
};

export const t = (key: string, lang: Language, options?: { [key: string]: string }): string => {
    const keyParts = key.split('.');
    let result: any = translations[lang];
    for (const part of keyParts) {
        if (result === undefined) break;
        result = result[part];
    }

    if (typeof result === 'string' && options) {
        return Object.entries(options).reduce((acc, [key, value]) => {
            return acc.replace(`{${key}}`, value);
        }, result);
    }

    return result || key;
};